export const data=[
{
  id:1,
  name:"CSE 299 Spring 22",
  faculty:"Kai Barua",
  image:"/../public/Honors.jpg",
  section:"4",
  avatar:"/../public/avt1.jpg",
},
{
  id:2,
  name:"CSE 311 Spring 22",
  faculty:"Semonti Barua",
  image:"/../public/bag1.jpg",
  section:"8",
  avatar:"/../public/avt3.jpg",
},
{
  id:3,
  name:"MAT361 Spring 22",
  faculty:"Nadeem Ahmed",
  image:"/../public/bag2.jpg",
  section:"11",
  avatar:"/../public/avt4.jpg",
},
{
  id:4,
  name:"MAT361 Spring 22",
  faculty:"Nadeem Ahmed",
  image:"/../public/Honors.jpg",
  section:"8",
  avatar:"/../public/avator.jpg",
},
{
  id:5,
  name:"MAT361 Spring 22",
  faculty:"Nadeem Ahmed",
  image:"/../public/bag2.jpg",
  section:"11",
  avatar:"/../public/avt4.jpg",
},
{
  id:6,
  name:"MAT361 Spring 22",
  faculty:"Nadeem Ahmed",
  image:"/../public/Honors.jpg",
  section:"8",
  avatar:"/../public/avator.jpg",
},
{
  id:7,
  name:"MAT361 Spring 22",
  faculty:"Nadeem Ahmed",
  image:"/../public/Honors.jpg",
  section:"8",
  avatar:"/../public/avt5.jpg",
},

]